service: tmdb-api-wrapper
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1
  memorySize: 128
functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
